version: '3.8'

services:
  api:
    build: .
    container_name: homepower-prueba-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: homepower
      POSTGRES_PASSWORD: homepower_password
      POSTGRES_DB: prueba_tecnica_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
